---
# 1. The Deployment (The Pods running your Java app)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-webapp
spec:
  replicas: 2 # Running two copies for corporate High Availability!
  selector:
    matchLabels:
      app: spring-webapp
  template:
    metadata:
      labels:
        app: spring-webapp
    spec:
      containers:
        - name: spring-webapp
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          image: spring-webapp:v3
          imagePullPolicy: Never # Tells K8s to use the sideloaded image, not the internet
          ports:
            - containerPort: 9443 # Your exotic port
          env:
            - name: SERVER_PORT
              value: "9443"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/springdb"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            # Securely pulling the credentials from the Kubernetes Secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "hobby-vault-provider"
            nodePublishSecretRef:
              name: secrets-store-creds

---
# 2. The Service (The stable internal network address)
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service # This MUST match what you put in Cloudflare!
spec:
  selector:
    app: spring-webapp
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
