apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# List ONLY the files you want Flux to deploy
resources:
  - secret-provider.yaml
  - postgres-infra.yaml
  - cloudflare-tunnel.yaml
  - app-deployment.yaml

commonLabels:
  managed-by: azure-arc-flux
  env: hobby-lab
