apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hobby-vault-provider
spec:
  provider: azure
  secretObjects: # This creates the "postgres-secret" you already use
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: pg-password # Name of secret in Azure Vault
          key: POSTGRES_PASSWORD # Key name your app expects
        - objectName: pg-user # Add your username to the vault too!
          key: POSTGRES_USER
    - secretName: cloudflare-secret
      type: Opaque
      data:
        - objectName: cf-tunnel-token
          key: TUNNEL_TOKEN
  parameters:
    keyvaultName: "hobby-vault-1819824795" # The name of your Azure Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    tenantId: "b6a9e683-c825-455c-9a40-4f4f8ff57324" # Run 'az account show' to find this
    objects: |
      array:
        - |
          objectName: pg-password
          objectType: secret
        - |
          objectName: pg-user
          objectType: secret
        - |
          objectName: cf-tunnel-token
          objectType: secret
